csv: datasets/processed/train.csv
seed: 42

save_dir: results/baselines

linear_fit_intercept: true

svr_kernel: rbf
svr_C: 1.0
svr_epsilon: 0.1
svr_gamma: scale

visualize: true
visualize_csv: datasets/processed/train_2304601.csv
visualize_title: Baselines
visualize_save: true
show_residual: true
