csv: datasets/5Gtraffic/number_value_cell_2_beam_19.csv
transfer_csv: datasets/5Gtraffic/number_value_cell_2_beam_27.csv
transfer: true
save_dir: results/5g_traffic_baselines/
batch: 256
train_rate: 0.8  # 0.8 -> many_shot; 0.2 -> few_shot
input_len: 36  # input_len
output_len: 36  # 36 -> long_term; 18 -> short_term
T: 1
D: 3
hidden: 64
layers: 1
device: cuda  # 0, 1, or cpu
seed: 2025
is_train: false
noise_test: true